name: Adum Inav CI

on:
  push:
    branches:
      - '**'
    tags:
      - "v*"
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0   # IMPORTANT: needed for git tags

      - name: Get version from latest tag
        id: version
        run: |
          TAG=$(git describe --tags --abbrev=0)
          BUILD=${{ github.run_number }}
          VERSION="${TAG}-${BUILD}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Log version
        run: echo "Building version ${{ steps.version.outputs.version }}"
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Install build dependencies
        run: |
          #sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc \
            g++ \
            ninja-build \
            gcc-arm-none-eabi
            
      - name: Build SITL
        run: |
          rm -rf build_SITL
          mkdir -p build_SITL
          cmake \
            -DSITL=ON \
            -DDEBUG=ON \
            -DWARNINGS_AS_ERRORS=OFF \
            -GNinja \
            -B build_SITL \
            .
          cd build_SITL
          ninja

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: inav-sitl-${{ steps.version.outputs.version }}
          path: build_SITL

      - name: Build MATEK F405 SE
        run: |
          rm -rf build
          mkdir -p build
          cmake \
            -DTARGET=MATEKF405SE \
            -DCMAKE_BUILD_TYPE=Release \
            -DWARNINGS_AS_ERRORS=OFF \
            -GNinja \
            -B build \
            .
          cd build
          ninja MATEKF405SE

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: inav-MATEKF405SE-${{ steps.version.outputs.version }}
          path: build



