name: Adum Inav CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Install build dependencies
        run: |
          #sudo apt-get update
          sudo apt-get install -y \
            cmake \
            gcc \
            g++ \
            ninja-build \
            gcc-arm-none-eabi
            
      - name: Build SITL
        run: |
          rm -rf build_SITL
          mkdir -p build_SITL
          cmake \
            -DSITL=ON \
            -DDEBUG=ON \
            -DWARNINGS_AS_ERRORS=OFF \
            -GNinja \
            -B build_SITL \
            .
          cd build_SITL
          ninja

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: inav-sitl
          path: build_SITL

      - name: Build MATEK F405 SE
        run: |
          rm -rf build
          mkdir -p build
          cmake \
            -DTARGET=MATEKF405SE \
            -DCMAKE_BUILD_TYPE=Release \
            -DWARNINGS_AS_ERRORS=OFF \
            -GNinja \
            -B build \
            .
          cd build
          ninja

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: inav-MATEKF405SE
          path: build



          
